### ISSUE TITLE
Proposal: Please close stale issues. Stalebot.

### ISSUE THREAD

**Issue by loganvolkers** [mozilla-services/react-jsonschema-form#1009]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

It seems like this repo has become pretty stale when it comes to open pull requests and issues.

I would like to propose that stale issues get closed. One tool that can help with that is https://github.com/probot/stale

In an ideal world with infinite resources, there would be no need for Stalebot.

But in any successful software project, there's always more work to do than people to do it. As more and more work piles up, it becomes paralyzing. Just making decisions about what work should and shouldn't get done can exhaust all available resources.

To some, a robot trying to close stale issues may seem inhospitable or offensive to contributors. But the alternative is to disrespect them by setting false expectations and implicitly ignoring their work. This app makes it explicit: if work is not progressing, then it's stale. A comment is all it takes to keep the conversation alive.

**Comment by glasserc** [comment]
I don't really see this as correct. Just because an issue hasn't had activity doesn't mean it's stale. Sometimes it describes a real bug that will take a lot of effort to fix, and because of the minimal maintenance effort this library receives, may never be fixed. Some of the issues in this repo *are* stale, but I think this is too blunt of an approach to be helpful.
