### ISSUE TITLE
Is jsonschema-from supported HTML maxlength attribute?

### ISSUE THREAD

**Issue by toanqc** [mozilla-services/react-jsonschema-form#1111]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description
I know we have a maxLength & minLength, but these attributes are for validation only. I want the HTML attribute maxlength that prevent user to input more that the value define to maxlength.

#### Expected behavior
Support HTML maxlength attribute

### Version
1.0.6

**Comment by glasserc** [comment]
rjsf generally does not try to prevent the user from entering data that doesn't fit the schema, so no. You could define a widget that tries to convert `minLength` and `maxLength` into HTML attributes if you wanted.

**Comment by SivaGanesh56** [comment]
if I create custom widget for this. shall i face any challenges like validations, onBlur events ...........

**Comment by guglodmv** [comment]
We have the same issue, should close this issue. It is fixable.

**Comment by guglodmv** [comment]
I would like to reopen this issue. The fix is src/components/fields/StringField.js add 

diff --git a/packages/core/src/components/fields/StringField.js b/packages/core/src/components/fields/StringField.js
index 4664f8e..0c91f9c 100644
--- a/packages/core/src/components/fields/StringField.js
+++ b/packages/core/src/components/fields/StringField.js
@@ -27,7 +27,7 @@ function StringField(props) {
     registry = getDefaultRegistry(),
     rawErrors,
   } = props;
-  const { title, format } = schema;
+  const { title, format, maxLength } = schema;
   const { widgets, formContext } = registry;
   const enumOptions = isSelect(schema) && optionsList(schema);
   let defaultWidget = enumOptions ? "select" : "text";
@@ -57,7 +57,7 @@ function StringField(props) {
       registry={registry}
       placeholder={placeholder}
       rawErrors={rawErrors}
+      maxlength={maxLength}
     />
   );
 }

**Comment by sanjeev16011994** [comment]
is maxlength featrue added
