### ISSUE TITLE
formData reactivity in ArrayField

### ISSUE THREAD

**Issue by victorzhuk** [mozilla-services/react-jsonschema-form#1161]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

While I'm creating custom `ArrayField` with custom `onAddClick` method, noitced, that `formData` is not reactive, and you should call `myFormRef.onChange(myData)` to force re-render form component. Is it bug or feature?

Looking at src of `ArrayField` I see that:
```
var _props3 = this.props,
...
formData = _props3.formData,
...;
```
Maybe this breaks reactivity?

### Version

1.2.0

**Comment by epicfaace** [comment]
Thanks for the issue report. Can you please include a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue?

**Comment by victorzhuk** [comment]
Sure! [click me](https://jsfiddle.net/zhukva/sk5x0jzu/)

**Comment by epicfaace** [comment]
Can't you just use `props.onAddClick` instead of defining your own `props.onContext.onAddClick`? Such as in this fiddle: https://jsfiddle.net/9wnb2uo1/

If you really need to define your own `props.onContext.onAddClick`, you have to call `myFormRef.onChange(myData)`; that is intended. Otherwise, with the line of code you have:
```
data = ['new test item', ...data]
```
You are just creating a variable named `data` and setting it to something. How else will you make the form aware of the changes in data unless you pass `data` back to the form through something like an `onChange` handler?

**Comment by victorzhuk** [comment]
I expect that `formData` prop is reactive, if you pass `data` and then change it - DOM should rerender, no need to call `onChange`. but sometimes when copy object (even without `Object.assign`) and use it's prop in render - maybe this breaks this reactivity behavior?

**Comment by pieplu** [comment]
> I expect that `formData` prop is reactive
> no need to call `onChange`

I'm not sure. But I think your issue is for React. And I don't think it's a bug. React simply does know if the variable (data in your case) is changed. 

To be re-rendered, a component should have a parent who said, "Hey! You! re-render!" or have a state modification (setState). (Except with react context API)

1. Your `data` variable should not be lost on your code like that. You should wrap all of it on a component, who have "data" on his state.
2. Your `formContext` function `onAddClick` should be a method of the component (who should access on "this.setState()". You can too use React Context API insted of the formContext props. but I don't think that is a good idea for this use case.

**Comment by victorzhuk** [comment]
Yep, you are right! [here](https://jsfiddle.net/zhukva/sk5x0jzu/40/) new code.
In additional: 
- for reactivity derive from `Component` and use `setState()`
- props are not reactive
- but if you need reactive props - use `PureComponent` or [memoize](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html)

thx for your answers and hope this helps someone else!

**Comment by epicfaace** [comment]
Great, glad your issue was fixed -- thanks @pieplu ! Closing this issue.
