### ISSUE TITLE
Adding default empty array items when initializing a form

### ISSUE THREAD

**Issue by matiaslarsson** [mozilla-services/react-jsonschema-form#134]
It would be very nice for the end user to have array items with minItems > 0 added by default when opening new empty forms instead of having to click "Add" and then start filling the item with data.

Should this be handled by react-jsonschema-form or is it out of scope?

If it's out of scope I guess one would have to create custom `ui:field` component which checks the schema for minItems and adds empty items required to pass the validation?

**Comment by n1k0** [comment]
I think that's a very good idea. It *shouldn't* be too hard to create an array field with `minLength` items with default value, but we're never too sure.

Would you like to work on this?

**Comment by matiaslarsson** [comment]
It's not at the top of our priorities right now and I have to switch projects for a while so it's probably best to keep this open for anyone to grab.

**Comment by apkoponen** [comment]
I started working on this, but after testing my initial implementation a while, I'm not sure what is the proper approach. I tried adding the items in the constructor, but I ran issues with the validation because the validation is triggered through super(props). In order to work around this, I would need to recall the validation method again in the constructor. Is the constructor a right place to do this?

Also, adding default items to the form feels quite unintuitive, when we are editing existing data that has not been created with the form, as there is a mix of default fields and fully completed ones.

**Comment by safareli** [comment]
I think it should support [minItems][https://github.com/json-schema/json-schema/wiki/Minitems] from json schema and if you have for example `minItems: 2` then 2 empty items should be created.

**Comment by martinpengellyphillips** [comment]
Would it make sense to use `default` for this?

**Comment by matiaslarsson** [comment]
Closed by #484. Great work @Reggino!
