### ISSUE TITLE
Custom label class

### ISSUE THREAD

**Issue by gr8pathik** [mozilla-services/react-jsonschema-form#1392]
### Prerequisites

- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [X] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description
I need to add a `custom class` in the `label` tag. I cannot find any way right now to add a custom class in the label tag. Is there any way to add?

#### Expected behaviour

There should have some property like `labelClassName` in `uiSchema` to add a custom class in label tag.

### Version

`"react-jsonschema-form": "^1.7.0"`

**Comment by gongpeione** [comment]
```
'ui:options': {
  class: 'custom-class'
}
```

**Comment by epicfaace** [comment]
@gr8pathik yeah, you are right. Perhaps rather than creating a new property like `labelClassName`, we can create a field such as `LabelField` which allows one to override the label completely. Or do you think it would be useful enough to be able to conveniently customize the label class name with something like `labelClassName` instead of needing to create an entire new field?

**Comment by epicfaace** [comment]
Merging this into #408.
