### ISSUE TITLE
Custom field validation

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/react-jsonschema-form#145]
Refs #144 and possibly other issues.

We should be able to define custom validation logic for fields:

```js
const schema = {
  type: "object",
  properties: {
    pass1: {type: "string", minLength: 8},
    pass2: {type: "string", minLength: 8},
  }
};

function validate({pass1, pass2}, error) {
  if (pass1 !== pass2) {
    return error("Passwords don't match");
  }
}

const uiSchema = {
  "ui:validate": validate,
  pass1: {"ui:widget": "password"},
  pass2: {"ui:widget": "password"},
};

render(<Form schema={schema} uiSchema={uiSchema} />);
```

We should also be able to registering these, as we do for custom fields and widgets. The `error` function should handle field error contextualization, so it might be bound appropriately with the field path. 

Not entirely sure these validators should be part of uiSchema or have their own container:

```js
const validatorSchema = {
  root: validate
};

render(<Form schema={schema} validatorSchema={validatorSchema} />);
```

Or simply 

```js
function validate({pass1, pass2}, error) {
  if (pass1 !== pass2) {
    return error("root.pass2", "Passwords don't match");
  }
}

render(<Form schema={schema} customValidate={validate} />);
```

Where the function will always be passed the whole `formData`, and the developer will have to specify the location of the error by hand.

Last, it appears more and more that validation and error handling could be made at the field level, as suggested by @rhgb in https://github.com/mozilla-services/react-jsonschema-form/pull/132#issuecomment-209976438, and so we would propagate errors a little like we propagate `formData` up the tree. That would obviously require some heavy refactoring, but quite possibly for the better. Also, that would allow defining custom validation logic and error propagation right from custom fields, which would be definitely convenient.

Decisions, decisions. Thoughts?

**Comment by n1k0** [comment]
We should probably examine https://www.npmjs.com/package/jsonschema#custom-formats for custom validation.

**Comment by n1k0** [comment]
I've started a tiny experiment in #163 about that, feedback welcome.

**Comment by n1k0** [comment]
The fix has landed as part of [v0.30.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.30.0).

**Comment by revolunet** [comment]
About [jsonschema custom formats](https://www.npmjs.com/package/jsonschema#custom-formats), being able to define custom formats could be useful if we dont want to use the custom form validate function.

Looks like jsonschema accepts custom formats on a validator instance basis so one solution could be to pass yet another `customFormats` props to the `<Form/>` ? 

My use case is a custom url validator, because [jsonschema one](https://github.com/tdegrunt/jsonschema/blob/master/lib/helpers.js#L123) is quite minimalistic.

Another solution would be to use a more powerful validator like https://github.com/epoberezkin/ajv maybe

**Comment by n1k0** [comment]
Wouldn't just writing your own [validate function](https://github.com/mozilla-services/react-jsonschema-form#custom-validation) solve your issue?

**Comment by revolunet** [comment]
yes thanks i've seen that but :

 - looks like the custom validation function is a second pass after the standard `validate()`. so you have to combine potential errors from the builtin validation with your own (ex: minLength + customValidation)

 - also when you have a custom validation for various schemas with various properties names it can be tricky to handle, but doable.

That said.... as @JonathanMontane pointed out, in my case, i can simply use `pattern` in the schema definition, so problem solved and sorry for the noise :) 🍻

**Comment by mattblackdev** [comment]
@n1k0 I believe I have a solid use case for field level validation. I am working on an enterprise application that allows users to build data types/collections, as well as custom forms to modify the records. I am providing a bunch of custom form fields with prebaked business logic for the users to add at whim to their forms. These custom fields use backend services and should encapsulate their own validation. As it is right now, they can't because they have no hooks into the form validation. Instead I think my options are either: 

1. Have a form container component generate a validation function on the fly based on ui:field properties, or
2. Make my custom field components render their own errors and have them make a call to a form container component to disable the submit button when they're invalid.

Option 1 sounds like running around the world to get on the other side of the fence. I think I'll try option 2 first, but even this seems wrong and I will have to make sure anytime I use a <Form/> component that I am controlling the submit.

After reading a few threads about similar issues I am surprised this project never made the leap to allow field level validation. So, I'm thinking maybe I'm missing something or approaching this wrong all together. Maybe I should be looking at custom SchemaField? Could you or anyone advise?

**Comment by glasserc** [comment]
Hi, I can't speak for Niko, but to me this doesn't really sound like a great use case for react-jsonschema-form. It seems to me like the data you describe do not have a schema described in JSON Schema. Indeed, JSON Schema only provides a few validation mechanisms; anything else you might want, you're on your own. (For example, JSON Schema does not allow you to validate that a given number is prime, nor that a given string is valid base64.) Given that what you are doing is describing data that cannot be described using JSON Schema, I think all uses of react-jsonschema-form will be quite challenging or awkward.

Niko suggested above that refactoring rjsf to generate *all* errors in a bottom-up fashion might be valuable, and doing that would certainly make supporting custom field validation easier. I'm not sure I agree, but I'd be willing to look at PR that made this change, and if it did indeed improve the quality of the library, I would be happy to merge it.

**Comment by mattblackdev** [comment]
@glasserc Thanks for the reply. You make a great point and my experience has been as you predicted. What I ended up doing so far is my 2nd option above, disabling the submit and having the custom field render it's own errors. It's feels crude and limited. I think what our project needs is as you say, a custom or more robust way to define a schema then we can generate the JSON Schema schema for editing data via react-jsonschema-form. However, I'm afraid this might take us down a path that abandons react-jsonshema-form all together.

**Comment by glasserc** [comment]
I think that's fine. I think a lot of people use rjsf as a one-size-fits-all form library, but actually rjsf has a very specific niche and I think it's just a lack of other form libraries in JS that make rjsf comparatively attractive.
