### ISSUE TITLE
Make form group collapsable

### ISSUE THREAD

**Issue by zengfenfei** [mozilla-services/react-jsonschema-form#268]
Since my schema has nested objects and is kind of large, it will be great help to collapse some of objects.

**Comment by n1k0** [comment]
This is definitely something we want indeed.

**Comment by n1k0** [comment]
As often, the hardest part is the UX here. I came with this for now, but am wondering how the UI could expose something convenient and not intrusive. Thoughts?

![](http://i.imgur.com/T57gvlu.png)

**Comment by amarnus** [comment]
I feel that it will be better to keep this functionality outside this module and instead support widgets for Array and Object fields in a better way so that people can build this functionality by themselves as a widget. Collapsing is just one option. You can also show as Tabs, for instance.

**Comment by n1k0** [comment]
Very true, and this lib does a lot already so we shouldn't bloat it up with more features most people won't ever need.

I'll look into #225 to see where we're at to have custom object and array widgets.

**Comment by n1k0** [comment]
A field template system as described in https://github.com/mozilla-services/react-jsonschema-form/issues/275#issuecomment-231948348 would indeed expose a convenient API to implement this. Let's do this.

**Comment by nuclearspike** [comment]
Being able to set a wrapping component of a fieldset would solve this. Then you could use tabs or collapsible sections, columns, or anything you wanted. I'd want to be able to define the wrapping component then an object that contains all the props to be passed to it (for tab titles, etc). I don't know that the field template system would be enough since isn't that only at the field level? Would we need a fieldset template?

**Comment by n1k0** [comment]
> Would we need a fieldset template?

Yeah this is a good idea, please comment on #281 about it.

**Comment by n1k0** [comment]
Now #304 has landed we can safely close this.
