### ISSUE TITLE
Should allow null with date input

### ISSUE THREAD

**Issue by vinhlh** [mozilla-services/react-jsonschema-form#300]
I have this error when saving a form with a date input,
`does not conform to the "date" format`

Should consider its value as null.

**Comment by Natim** [comment]
Is your date field required?

**Comment by mplis-jetsetter** [comment]
@vinhlh could you provide more details? The only way I can reproduce this error in the [playground](https://mozilla-services.github.io/react-jsonschema-form/) is if I go to the "Date & time" tab and manually mess with the formData editor. I can't reproduce the error from simply using the form.

**Comment by vinhlh** [comment]
@mplis-jetsetter 

Change to `Date & Time` tab, try to set a value for Date field, Click (X) icon on the right of the input, and you will get this message `does not conform to the "date" format`

**Comment by n1k0** [comment]
@vinhlh I can't reproduce, what browser/version are you using?

**Comment by mplis-jetsetter** [comment]
@n1k0 I can reproduce on Chrome v51.0.2704.106, but only with the date widget, not the datetime one. Steps:

1. Enter a valid date into the date widget so that the formData contains `native.date`
2. Click the X button in the date widget to clear the values

This causes `native.date` to be equal to `""`, whereas if you perform the same actions above for the datetime widget, clicking the X button clears the key from the formData.

**Comment by vinhlh** [comment]
@n1k0 
latest Chrome v52.
![](http://i.imgur.com/CQSQbuc.png)

![](http://i.imgur.com/1fAhCTM.png)

**Comment by n1k0** [comment]
I'm on it.
