### ISSUE TITLE
Styling difficulties for ObjectField's fieldset 

### ISSUE THREAD

**Issue by misto** [mozilla-services/react-jsonschema-form#443]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I'm having problems styling a fieldset, I'm creating a signup form and want first- and lastname fields to appear side by side, using the fieldset as a flex container. This works fine in Firefox but [not in Chrome](https://code.google.com/p/chromium/issues/detail?id=262679). Is there any workaround for this? Except copying the whole ObjectField implementation, and e.g. wrapping the fields in another div which then can be the flex container.

### Steps to Reproduce

See the [sample JSFiddle](https://jsfiddle.net/f2y3fq7L/12/).

**Comment by n1k0** [comment]
There's no known workaround about this nor we do have time to investigate how to fix specific styling issues. Feel free to provide a PR if you've identified a generic fix for this.

**Comment by vamsiampolu** [comment]
I am having issues wrapping the `ObjectField` inside a `css-in-js` solution like `styled-components` or `glamor` which generate real css because the `fieldset` does not recieve a `className` or `style` prop from the `ObjectField` even though the library creates a css class and passed a className to ObjectField.

```js
import styled from 'styled-components'

const CustomObjectField = styled(ObjectField)`
    border: 0 none;
`
```

I found in my react-dev-tools that:

```
$r.state.generatedClassName
"gdSuUl"
```

from the styled component and the `$r.props.className` is `"gdSuUl"`. When I checked the fieldset, no class was assigned to it, I had to use the `injectGlobal` to solve the issue

```js
injectGlobal`
  fieldset {
    border: 0 none;
  }
`
```

**Comment by glasserc** [comment]
@vamsiampolu If I understand correctly, your concern is that the `fieldset` element is created without a class or style. But many elements in rjsf are created without classes or styles -- for example, a `div` and a `p` are created in `ErrorList` that don't have any style information whatsoever, and there are many elements that are created with hard-coded `className` (like elements in `ErrorList`). How could we add classes to certain elements without it becoming unmaintainable? Is there a specific change you'd like to see? Feel free to open a PR if you want to discuss it further!
