### ISSUE TITLE
Support Foundation 6

### ISSUE THREAD

**Issue by developer-lindner** [mozilla-services/react-jsonschema-form#555]
Just stumbled upon this React Plugin and wondered if something like Foundation could be considered. Already tried to use FieldTemplate etc. but it's not that easy at all.

**Comment by glasserc** [comment]
What's challenging about it?

I don't think anyone is opposed to other CSS frameworks, but we support Bootstrap because it's what we use. I'm a little nervous about adding support for specific CSS frameworks directly to this library when we don't support them. I'd much rather let people offer extensions that support whatever their favorite framework is. If there's something needlessly challenging about implementing those extensions as FieldTemplate bundles, I'd like to talk about that and maybe we can resolve it. I guess I'm not philosophically opposed to adding some other kind of hook to support CSS frameworks, but that would add complexity and I don't know what that hook would look like yet. Do you have any specific ideas?

**Comment by Cactucs** [comment]
HI!
I'm working with material design lite, but I am using this lib also. And in some cases the result is not that it does not have styles, but that it's unusable (e.g. buttons in array field are small and empty because I do not have the icon font).

Maybe if the UI would be separate from the logic and I would be able to supply some or even all UI components.

**Comment by glasserc** [comment]
Hi @Cactucs, the UI is already somewhat separated from the logic -- that's why we support e.g. [custom widgets and fields](https://github.com/mozilla-services/react-jsonschema-form#custom-widgets-and-fields). Is that not sufficient for what you need? Could you clarify what you'd like to see added or changed? It's true that ArrayField is of limited customizability right now -- I guess that's what #567 is about. I'd be willing to review patches to add customizability if we can do it cleanly without adding a lot of complexity.

**Comment by ztolley** [comment]
I like the sound of field template bundles. I want to use something that is more semantically correct than bootstrap to allow for better accessibility.

**Comment by epicfaace** [comment]
Closing this in favor of #899.
