### ISSUE TITLE
What purpose does safeRenderCompletion serve?

### ISSUE THREAD

**Issue by olzraiti** [mozilla-services/react-jsonschema-form#562]
Hey there,

I solved a bug in my application by setting the undocumented `safeRenderCompletion` to `true` (it's `false` by default).
The `safeRenderCompletion` affects the Form `onChange` function like this:

- if it is `true`, `onChange` calls `props.onChange` IMMEDIATELY after `this.setState({formData})`.
- if it is `false`, `onChange` calls `props.onChange` in the usual way after state has been updated like this: `this.setState({formData}, onChange)`.

Now, I'm using a wrapper for the `Form`, and one custom field is triggering a state change to the wrapper and calling `props.onChange` consequently, and if `safeRenderCompletion` is `false`, the state is updated but the changes of the `onChange` event are lost, because `Form`'s internal state rewrites it after the onChange is set immediately. (Yes, manipulating the wrapper component from a child component is kind of hacky, but it's what you have to do if you need to affect the global state. In this use case I'm displaying a blocking loader for the duration of a promise chain.)

The use case is complicated and difficult to explain, and I can try to write an understandable example of what I'm trying to do, but before that (also, **if ;TLDR, read below**):

I'd like to know why the behaviour with `safeRenderCompletion` is needed, since it seems a bit dangerous. I'm guessing it's for performance - has the impact been measured?

The tests set `safeRenderCompletion`to `true`, so the unsafe behaviour of `safeFenderCompletion` being `false` isn't tested (it's `'false` by default!)

**Comment by olzraiti** [comment]
I didn't notice #544 - I`ll close this

**Comment by emirotin** [comment]
Hmmm, I'm actually not sure what's happening here but I've just hit an issue (spent quite some time debugging it) on a pretty fast CPU (newest MBP). Apparently, I've been editing a form with type `array` and the custom widget for array elements (strings, but picked using the special widget), and my form was always reset to `[null,null,null]` immediately after each save because without this param the callback is set with the current state before the state is updated with the new data
