### ISSUE TITLE
about the validation

### ISSUE THREAD

**Issue by eddyzhang1986** [mozilla-services/react-jsonschema-form#614]
### Steps to Reproduce

1. Demo https://eddyzhang1986.github.io/antd-jsonschema-form/
2. Schema: 
```jsx
const schema = {
  title: "Todo",
  type: "object",
  required: ["title"],
  properties: {
    title: { type: "string", title: "Title", default: "A new task" },
    title2: { type: "string", title: "Title", default: "A new task2" },
    done: { type: "boolean", title: "Done?", default: false }
  }
};
```
3. Set an empty value for the `title` field
4. Click `Submit`
5. Both `title` and `title2` are marked in error in red

**Comment by mavarazy** [comment]
This can also be reproduced on https://mozilla-services.github.io/react-jsonschema-form/ 
In the first simple form both firstName and lastName required, but when removing value from firstName nothing happens, while when editing lastName form turns red.

**Comment by mavarazy** [comment]
I've found a problem in https://github.com/tdegrunt/jsonschema component and opened appropriate issue there.

For your use case, you can move required to specific field and it will work as expected

     const schema = {
       title: "Todo",
      type: "object",
      properties: {
        title: { type: "string", title: "Title", default: "A new task", required: true },
        title2: { type: "string", title: "Title", default: "A new task2" },
        done: { type: "boolean", title: "Done?", default: false }
      }
    };

**Comment by eddyzhang1986** [comment]
@mavarazy hi,thanks for help.
But, "required:true or false"here seems not base the rule of IETF jsonschema specification

**Comment by epicfaace** [comment]
@eddyzhang1986 , this seems to have been fixed in the [latest version](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJ0aXRsZTIiOiJhIiwiZG9uZSI6ZmFsc2V9LCJzY2hlbWEiOnsidGl0bGUiOiJUb2RvIiwidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbInRpdGxlIl0sInByb3BlcnRpZXMiOnsidGl0bGUiOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiVGl0bGUifSwidGl0bGUyIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlRpdGxlIn0sImRvbmUiOnsidHlwZSI6ImJvb2xlYW4iLCJ0aXRsZSI6IkRvbmU/IiwiZGVmYXVsdCI6ZmFsc2V9fX0sInVpU2NoZW1hIjp7fX0=).

Closing this; feel free to comment if you're still having a problem.
