### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by santosguilherme** [mozilla-services/react-jsonschema-form#790]
Is this project still maintained?

**Comment by doncesarts** [comment]
You can check  the activity of the project  here https://github.com/mozilla-services/react-jsonschema-form/graphs/commit-activity

**Comment by santosguilherme** [comment]
Why does no one respond to issues and the pull requests?

**Comment by edi9999** [comment]
I have just received an invitation from @Natim to become a collaborator.

I have accepted this invitation. However, I still cannot do actions such as "merging", "closing issues", ... 

@Natim Can you check to give me those rights, if that was indeed your intention ?

**Comment by glasserc** [comment]
Mozilla nominally maintains this project, but because it is feature complete from our point of view, there is very little maintenance effort allocated on our side to it. I try to check in once a week, but the last month or so have been the holidays, plus fighting a fire, and so I haven't really had the time to do so. See also https://github.com/mozilla-services/react-jsonschema-form/pull/623#issuecomment-331579516 and #707.

@Natim flagged that @edi9999 had started contributing recently and asked if I thought it was OK to extend the invite. I have changed your status to have write permission.

@santosguilherme, feel free to fork this project and merge any features from the PRs you think are good. If your fork takes off, I think we would be happy to use it instead.
