### ISSUE TITLE
Clarification of current support for conditional fields

### ISSUE THREAD

**Issue by donalmurtagh** [mozilla-services/react-jsonschema-form#816]
I've read the relevant documentation and issues, and just want to clarify the current position with respect to conditional fields. Given the following schema

```
const schema = {
    "title": "Consent form",
    "type": "object",
    "required": ["age", "parentalApproval"],
    "properties": {
        "age": {
            "type": "number",
            "title": "Age"
        },
        "parentalApproval": {
            "type": "boolean",
            "title": "Do you have approval of a parent?"
        }
    }
};
```

The requirement is that the `parentalApproval` should only be displayed if the `age` field is less than 18, (therefore the inclusion of `parentalApproval` in the list of `required` fields should be interpreted as "required if visible").

My understanding is that there is no way to specify this condition in either the JSON schema or the UI Schema. The recommended way to implement this requirement is by programmatically modifying the schema in the `onChange` event as shown in [this example](https://jsfiddle.net/69z2wepo/88541)?

If there's a simpler way to implement this requirement, could someone please show me how?

**Comment by elboletaire** [comment]
Apparently, no. There's no a simpler way. I'm trying to add an "Others" field to a list of checkboxes and due to #841 I need to follow this example: https://jsfiddle.net/cowbellerina/zbfh96b1/ which forces me to add more than 150 lines, and also modify the current behavior of my app.

So... at this point, I start to think that it would have been a better choice not using this library for forms (for a matter of time)...

**Comment by donalmurtagh** [comment]
@elboletaire since I opened this issue, I discovered there is a much simpler way to implement conditional fields, using [react-jsonschema-form-conditionals](https://github.com/RxNT/react-jsonschema-form-conditionals).

I tried using it one of my projects and it worked great. Very easy to use and extend.

**Comment by elboletaire** [comment]
Thanks for the suggestion @donalmurtagh. In fact, I see they also have an "extras" package with a field type named "Composite Array", which apparently is exactly what I'm trying to do.

I'm gonna give it a try right now.

**Comment by glasserc** [comment]
Hi, at this time rjsf has no way to support any kind of complicated requirement such as this. I guess you could express this logic using JSON Schema using `oneOf`, but being smart about what that schema "means" and updating the display accordingly sounds really hard and maybe even outside the scope of rjsf. The existing conditional logic is definitely not enough to handle it. I'm glad you found the "conditionals" library, which I hadn't known about. Maybe that's the best place for this logic.

**Comment by elboletaire** [comment]
@glasserc couldn't the code from [this example](https://jsfiddle.net/cowbellerina/zbfh96b1/) be added to rjsf somehow? I finally used that code without changes in my implementation and was really useful despite the required changes in my app.

@donalmurtagh fyi, I finally did not use the suggested plugin because it was causing strange behaviors in my app's events (using react-redux, which may be related).

**Comment by glasserc** [comment]
@elboletaire I'm glad that the conditionals from that example worked for you. But they aren't JSON Schema, which means that even if the code to support them were small and easy to maintain, I still wouldn't want it in rjsf. rjsf is already relatively complicated, and I think hiding/showing fields based on the values of other fields, done in a robust/elegant way, will be a major undertaking. I don't think the approach in the example is up to that standard, although I'm glad it was useful to you.
