### ISSUE TITLE
Expose progress events when using FileWidget

### ISSUE THREAD

**Issue by domurtag** [mozilla-services/react-jsonschema-form#921]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I use the [FileWidget](https://github.com/mozilla-services/react-jsonschema-form/blob/master/src/components/widgets/FileWidget.js) to allow users to to upload files.

I would like to show a spinner while the transfer is in progress, and hide it when it completes. Normally this would be achieved by [handling events](https://www.nczonline.net/blog/2012/05/22/working-with-files-in-javascript-part-3/) such as `loadstart` and `loadend`. 

However, this doesn't seem possible at the moment, because there's no way to access the `FileReader` object that exposes these events.

### Version

1.0.3

**Comment by domurtag** [comment]
@glasserc I don't think this issue should be closed. Essentially what you're saying is that if a widget lacks a capability, the recommended solution is to replace it with your own widget that provides the capability. Wouldn't a better solution be to add that capability to the default widget?

The difference between this issue and and #912 is that I didn't need to replace the entire widget in order to achieve the desired functionality.

**Comment by glasserc** [comment]
My feeling is that `FileReader` is not a good fit for the React philosophy of UI being defined as a pure function of state. FileReader is tied to the style of APIs where DOM objects are mutated. If we refresh the view and replace the FileWidget, we'll get a new `FileReader`, which will be different from the previous one even though the state is the same.

Additionally, files aren't really part of the JSON Schema standards, nor is uploading data to a server. These facts mean that what you're trying to do is outside the scope of the rjsf library. Because I can barely support what the rjsf project does today, adding more functionality to it is infeasible. Instead I'd like people to have the opportunity to, where it makes sense, extend rjsf to do whatever non-JSON-Schema things they want to do. In this case, that means overriding the FileWidget, for which a mechanism already exists.

**Comment by domurtag** [comment]
> If we refresh the view and replace the FileWidget, we'll get a new FileReader, which will be different from the previous one even though the state is the same.

What exactly do you mean by "refresh the view", e.g. reload the page? In that case whatever files were uploaded (to the browser) would be lost, so the state wouldn't be the same.

**Comment by glasserc** [comment]
If we change the JSON Schema, we have to rerender the form. React's Virtual DOM implementation may be smart enough to determine that the FileWidget is the same and so does not need to be rerendered, or it may not be.

**Comment by domurtag** [comment]
You seem to be suggesting that the JSON Schema would have to be changed at runtime in order to support the functionality I'm proposing.

I don't think we need anything more than a few additional props in `FileWidget` so that functions can be called on certain `FileReader` events such as `loadstart` and `loadend`.

**Comment by glasserc** [comment]
No, that isn't what I'm trying to communicate. My argument is that `FileWidget` generally is a bad fit for React. In general, the design of React encourages all state to be in JavaScript memory, and treats the DOM as a replica of the application state. This gives us nice properties such as when we change the JSON Schema, the application automatically adapts by just rerendering the entire form. React also has the ability to compare the current DOM against the previous DOM, but this is a performance optimization (it isn't required for correctness). React is perfectly within its rights to throw everything away and recreate a bunch of `<input>` fields with the `value` set to whatever is in the state.

By contrast, `<input type="file">` is an old-school DOM API. These APIs encourage all state to be in DOM objects maintained by the browser, and only occasionally read into JS memory. When using a `FileWidget`, we can no longer throw away an existing `<input>` element and create a new one with the same `value`. Once this happens, we have to rely on the DOM diffing that React does, not just for performance, but also for correctness (otherwise we lose files). This is a major pain and has already bit us with other "fancy" input elements -- see e.g. #895. Not to say that you can't make it work -- I think you probably could for certain applications! -- but you're swimming upstream.

`FileReader` does not itself store its data in the DOM, but it doesn't seem like something that can be recreated from application state, so I feel like it's in the same category. Exposing it to users seems dangerous. I'm OK with users introducing that danger to their own application but I don't want rjsf to be itself at risk.

**Comment by domurtag** [comment]
OK, I understand your objection now. Thanks for your response.
