### ISSUE TITLE
Use HTML elements in field help

### ISSUE THREAD

**Issue by donalmurtagh** [mozilla-services/react-jsonschema-form#926]
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

I would like to use HTML in the help text for some fields. I've tried everything I can think of:

#### String

```javascript
  const uiSchema = {
    myField: {
      "ui:help": '<div className="sidebar">some help</div>'
    }
  };
```

#### JSX

```javascript
  const uiSchema = {
    myField: {
      "ui:help": <div className="sidebar">some help</div>
    }
  };
```

#### Element

```javascript
  const uiSchema = {
    myField: {
      "ui:help": React.createElement('div', {className: 'sidebar'}, 'some help')
    }
  };
```
But none of these work

### Version
1.0.3

**Comment by doncesarts** [comment]
@donalmurtagh  
You will need to create a custom widget  or  to customised the field in order to render "ui:help" with html.

Your code will look like something like this. 
`<div dangerouslySetInnerHTML={createMarkup()} />`


More info: https://zhenyong.github.io/react/tips/dangerously-set-inner-html.html

Be aware of the danger that represents to insert html inside your form fields. 
https://stackoverflow.com/questions/37337289/react-js-set-innerhtml-vs-dangerouslysetinnerhtml

Regards

**Comment by knilink** [comment]
the code shows that it accept react elements
https://github.com/mozilla-services/react-jsonschema-form/blob/e0192b75d24024370d52a43293931c8ddd769752/src/components/fields/SchemaField.js#L70-L73
and it works just fine.
https://jsfiddle.net/yvqwaLj4/

**Comment by donalmurtagh** [comment]
@knilink I did some further experimentation and it seems JSX works when used within a class component (a subclass of `React.Component`), but not in a functional component

**Comment by epicfaace** [comment]
@donalmurtagh it seems like the JSX works in my example, which is a functional component -- https://jsfiddle.net/epicfaace/3a7bcufe/

I'm closing this issue, but please provide an example if you think it's still not working.
