### ISSUE TITLE
default value does not work

### ISSUE THREAD

**Issue by KunWangV** [mozilla-services/react-jsonschema-form#975]
```java
{
  "title": "Person",
  "type": "object",
  "properties": {
    "Do you have any pets?": {
      "type": "string",
      "enum": [
        "No",
        "Yes: One",
        "Yes: More than one"
      ],
      "default": "No"
    }
  },
  "required": [
    "Do you have any pets?"
  ],
  "dependencies": {
    "Do you have any pets?": {
      "oneOf": [
        {
          "properties": {
            "Do you have any pets?": {
              "enum": [
                "No"
              ]
            }
          }
        },
        {
          "properties": {
            "Do you have any pets?": {
              "enum": [
                "Yes: One"
              ]
            },
            "How old is your pet?": {
              "type": "number"
            }
          },
          "required": [
            "How old is your pet?"
          ]
        },
        {
          "properties": {
            "Do you have any pets?": {
              "enum": [
                "Yes: More than one"
              ]
            },
            "Do you want to get rid of any?": {
              "type": "boolean",
              **"default": false;**
            }
          },
          "required": [
            "Do you want to get rid of any?"
          ]
        }
      ]
    }
  }
}
```

as shown in the code,  the default value for "Do you want to get rid of any?" does not work!

**Comment by doncesarts** [comment]
Hi @KunWangV , You have a typo in your schema definition the character `;`  in the "default" definition of "Do you want to get rid of any?" . Apart from that it is working the default value as expected.

```
{
  "title": "Person",
  "type": "object",
  "properties": {
    "Do you have any pets?": {
      "type": "string",
      "enum": [
        "No",
        "Yes: One",
        "Yes: More than one"
      ],
      "default": "No"
    }
  },
  "required": [
    "Do you have any pets?"
  ],
  "dependencies": {
    "Do you have any pets?": {
      "oneOf": [
        {
          "properties": {
            "Do you have any pets?": {
              "enum": [
                "No"
              ]
            }
          }
        },
        {
          "properties": {
            "Do you have any pets?": {
              "enum": [
                "Yes: One"
              ]
            },
            "How old is your pet?": {
              "type": "number"
            }
          },
          "required": [
            "How old is your pet?"
          ]
        },
        {
          "properties": {
            "Do you have any pets?": {
              "enum": [
                "Yes: More than one"
              ]
            },
            "Do you want to get rid of any?": {
              "type": "boolean",
              "default": false
            }
          },
          "required": [
            "Do you want to get rid of any?"
          ]
        }
      ]
    }
  }
}
```

Copy and paste that on https://mozilla-services.github.io/react-jsonschema-form/ , it works. 

Regards

**Comment by KunWangV** [comment]
I cannot get the expected result using your code, are you sure it is ok?

**Comment by cmawhorter** [comment]
my guess is that OP is running into the same problem i am.  if the initial formData contains any value other than `undefined` for a property (like `null`), default will be ignored.

that's correct, but unexpected, especially when dealing with non-required fields.

IMO -- null for non-required fields should be stripped and not fail validation, since there is no way for an end-user to enter a value of `null`.

json schema supports multiple types e.g. `something: { type: [ 'string', 'null' ] }`.  if this lib supported that, this would be a non-issue.

but as it stands right now, you need to preprocess data and strip all null values before handing it off to jsonschema-form or else it'll force your user to interact with a non-required field.

An example for https://mozilla-services.github.io/react-jsonschema-form/

```json
{
  "type": "object",
  "properties": {
    "notrequired": {
      "type": "string",
      "title": "Not required",
      "minLength": 0,
      "default": "fdsa"
    }
  }
}
```

formData
```json
{
  "notrequired": null
}
```

With that, there is no way to submit the form.

This uischema doesn't help matters either: `{ "notrequired": { "ui:emptyValue": "" } }`

**Comment by jduncanRadBlue** [comment]
Any updates here?  I have a complex form that starts with a single drop down box.  The form is populated based off of what is selected using the dependencies.  I have several default values that need to be pre-populated.  Anyone know how to get the default value to work here?

**Comment by glasserc** [comment]
I think this issue is not really coherent so I'm going to close it.

As mentioned by @doncesarts, when I fix the typo in the JSON schema, it seems to work OK (an empty `formData` becomes `{"Do you have any pets": "No"}`, and selecting `Yes: More than one` auto-fills `"Do you want to get rid of any?": false`).

@cmawhorter: default values aren't applied when existing values are present. Yes, that includes null, false, empty arrays, or any other JSON-allowed value. I don't really expect that behavior to change. rjsf generally doesn't try to "clean" data.

@jduncanRadBlue, if your issue is not addressed by the above remarks, maybe it would be better to open a new issue.

**Comment by cmawhorter** [comment]
@glasserc The change @doncesarts mentioned does not work.  I copy the typo-less schema into the live editor and hit submit and result: `{}`.  It should be: `{ "Do you have any pets?": "No" }`, because No is the default.

I'm not talking about sanitizing the data as much as I'm talking about a limitation in this lib that can't be worked around.  

Getting back to the pets schema.  The default value for "Do you have any pets?" is pointless because it's impossible to ever use it (as far as rjsf is concerned).

**Comment by jduncanRadBlue** [comment]
@glasserc The change @doncesarts mentioned does not work for me either.  The part that I'm concerned with is the dependencies.  I need to be able to specify default values for fields.  I am not able to get those default values to render.

**Comment by glasserc** [comment]
@cmawhorter I just tried pasting the typo-less schema into the playground and replacing the `formData` with `{}` and it was immediately replaced with

```
{
  "Do you have any pets?": "No"
}
```

Clicking `Submit` caused it to log exactly the same object to the log. It sounds like you're seeing something else so please feel free to open another issue to describe what exactly you're doing and what exactly you're seeing.

@jduncanRadBlue Here is the same pet schema with a schema dependency on the field which *has* a  default as well as *providing* a default.

```
{
  "title": "Person",
  "type": "object",
  "properties": {
    "Do you have any pets?": {
      "type": "string",
      "enum": [
        "No",
        "Yes: One",
        "Yes: More than one"
      ],
      "default": "Yes: One"
    }
  },
  "required": [
    "Do you have any pets?"
  ],
  "dependencies": {
    "Do you have any pets?": {
      "oneOf": [
        {
          "properties": {
            "Do you have any pets?": {
              "enum": [
                "No"
              ]
            }
          }
        },
        {
          "properties": {
            "Do you have any pets?": {
              "enum": [
                "Yes: One"
              ]
            },
            "How old is your pet?": {
              "type": "number",
              "default": 21
            }
          },
          "required": [
            "How old is your pet?"
          ]
        },
        {
          "properties": {
            "Do you have any pets?": {
              "enum": [
                "Yes: More than one"
              ]
            },
            "Do you want to get rid of any?": {
              "type": "boolean",
              "default": false
            }
          },
          "required": [
            "Do you want to get rid of any?"
          ]
        }
      ]
    }
  }
}
```

Replacing the `formData` with `{}` caused it to produce

```
{
  "Do you have any pets?": "Yes: One",
  "How old is your pet?": 21
}
```

As previously mentioned, since this issue doesn't really make sense, please feel free to open a new one.

**Comment by epicfaace** [comment]
@MatinF thanks for your report, it does seem to be an issue with using `default` and `oneOf`/`anyOf`. Can you please make a playground link (https://mozilla-services.github.io/react-jsonschema-form/) with your example and make another issue for this?

**Comment by MatinF** [comment]
@epicfaace I've now added this as a new issue with an example as requested:
https://github.com/mozilla-services/react-jsonschema-form/issues/1293
